version: 2

jobs:
  cats:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "Purrr"
          command: |
            tail -c 11 ./images/cat.jpg

workflows:
  totallyacat:
    jobs:
      - cats
 
